apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 1.6.2
    helm:
      releaseName: mlflow
      valuesObject:
        service:
          type: ClusterIP
          port: 5000
        auth:
          enabled: false
          
        # Вимикаємо стару базу
        postgresql:
          enabled: false

        # ✅ ОФІЦІЙНИЙ СПОСІБ: Вказуємо зовнішню БД
        backendStore:
          postgres:
            host: "mlflow-postgres-postgresql.application.svc.cluster.local"
            port: 5432
            user: "mlflow"
            password: "mlflowpass"
            database: "mlflow"

  destination:
    namespace: application
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true